server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/on_line_answer
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  mvc:
    view:
      suffix: .html
      prefix: /
    static-path-pattern: /**

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  map-underscore-to-camel-case: true
  type-aliases-package: com.apesource.pojo

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

